# Generated by Django 2.1.7 on 2019-03-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='firstPhoto',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='firstText',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='firstTitle',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='information',
            name='fourthPhoto',
        ),
        migrations.RemoveField(
            model_name='information',
            name='fourthText',
        ),
        migrations.RemoveField(
            model_name='information',
            name='fourthTitle',
        ),
        migrations.RemoveField(
            model_name='information',
            name='secondPhoto',
        ),
        migrations.RemoveField(
            model_name='information',
            name='secondText',
        ),
        migrations.RemoveField(
            model_name='information',
            name='secondTitle',
        ),
        migrations.RemoveField(
            model_name='information',
            name='thirdPhoto',
        ),
        migrations.RemoveField(
            model_name='information',
            name='thirdText',
        ),
        migrations.RemoveField(
            model_name='information',
            name='thirdTitle',
        ),
    ]
