# Generated by Django 2.2.4 on 2019-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190413_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
