# Generated by Django 2.2.4 on 2019-08-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('identification', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first', models.CharField(max_length=80)),
                ('last', models.CharField(default='', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
            ],
        ),
    ]
