# Generated by Django 2.1.7 on 2019-06-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='firstName',
            new_name='first',
        ),
        migrations.AddField(
            model_name='coupon',
            name='last',
            field=models.CharField(default='', max_length=80),
        ),
    ]
