# Generated by Django 2.1.7 on 2019-06-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20190629_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='identification',
            field=models.IntegerField(max_length=7, unique=True),
        ),
    ]
