# Generated by Django 2.1.7 on 2019-06-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_auto_20190629_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='identification',
            field=models.IntegerField(unique=True),
        ),
    ]
