# Generated by Django 2.2.4 on 2019-08-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmemory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='born',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='passed',
            field=models.DateField(blank=True),
        ),
    ]
